name: Build and Publish

on:
  push:
    tags:
      - "*"

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: NPM tasks

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        run: |
          npm install --save-dev

          npm run build
          npm run pack

          npm publish

      - name: Release
        uses: softprops/action-gh-release@v1

        with:
          files: |
            quilt-bulma.zip
            dist/*

      - uses: actions/upload-artifact@v3
        name: Upload Artifact

        with:
          name: quilt-bulma.zip
          path: quilt-bulma.zip
